version: '2'

services:
  # Start messaging broker
  rabbitmq:
    image: rabbitmq:3.6.5-management
    ports:
      - "5672:5672"
      - "15672:15672" #Management Server
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "HKGyyiLGIy7t87or732r92r"

  # Start transformation worker
  strokewidthtransform:
    image: lex/open-ocr-preprocessor
    volumes:
      - ./scripts/:/opt/open-ocr/
    dns: ["8.8.8.8"]
    depends_on:
      - rabbitmq
    command: "/opt/open-ocr/open-ocr-preprocessor -amqp_uri amqp://admin:HKGyyiLGIy7t87or732r92r@rabbitmq/ -preprocessor stroke-width-transform"

  # Start PDF worker
  convertpdf:
    image: lex/open-ocr-preprocessor
    volumes:
      - ./scripts/:/opt/open-ocr/
    dns: ["8.8.8.8"]
    depends_on:
      - rabbitmq
    command: "/opt/open-ocr/open-ocr-preprocessor -amqp_uri amqp://admin:Phaish9ohbaidei6oole@rabbitmq/ -preprocessor convert-pdf"

  # Start OCR worker
  openocrworker:
    image: lex/${OPEN_OCR_INSTANCE}
    volumes:
      - ./scripts/:/opt/open-ocr/
    dns: ["8.8.8.8"]
    depends_on:
      - rabbitmq
    command: "/opt/open-ocr/open-ocr-worker -amqp_uri amqp://admin:HKGyyiLGIy7t87or732r92r@rabbitmq/"

  # Start http server
  openocr:
    image: lex/${OPEN_OCR_INSTANCE}
    volumes:
      - ./scripts/:/opt/open-ocr/
    ports:
      - "9292:9292"
    dns: ["8.8.8.8"]
    depends_on:
      - rabbitmq
      - openocrworker
      - strokewidthtransform
    command: "/opt/open-ocr/open-ocr-httpd -amqp_uri amqp://admin:HKGyyiLGIy7t87or732r92r@rabbitmq/ -http_port 9292"
